services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: rag_assistant
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: